### ISSUE TITLE
Moneyflow tests: fix TODOs after Mike's commit

### ISSUE THREAD

**Issue by AnthonyAkentiev** [Thetta/Thetta-DAO-Framework#163]
// TODO That worked with checkContractThrows but doesn't work with rejectedWith('revert')

## See these lines:

https://github.com/Thetta/Thetta-DAO-Framework/commit/78b30da3d867bedf7bd5eddfd296c8fb9ce71df9#diff-e040b06379f9d3f7508fe9afd6f50071R755

https://github.com/Thetta/Thetta-DAO-Framework/commit/78b30da3d867bedf7bd5eddfd296c8fb9ce71df9#diff-e040b06379f9d3f7508fe9afd6f50071R667

...

**Comment by enkogu** [comment]
Смотрим, что 
![image](https://user-images.githubusercontent.com/26708829/42467403-7b9a9f40-83ba-11e8-9e3f-a7bd3a483bac.png)

Делаем вот так
![image](https://user-images.githubusercontent.com/26708829/42467420-88f6ef04-83ba-11e8-9763-b9c73f689ae7.png)

Получаем
![image](https://user-images.githubusercontent.com/26708829/42467440-933f87c8-83ba-11e8-89ad-b37f8df81171.png)

**Comment by AnthonyAkentiev** [comment]
@Mikelle Поправь, плиз. Выше Кирилл тебе ответил, в чем дело

**Comment by Mikelle** [comment]
@enkogu @AnthonyAkentiev А что насчет этой строчки [](https://github.com/Thetta/Thetta-DAO-Framework/commit/78b30da3d867bedf7bd5eddfd296c8fb9ce71df9#diff-e040b06379f9d3f7508fe9afd6f50071R460) ?

**Comment by enkogu** [comment]
```AssertionError: expected promise to be rejected with an error including 'revert' but got 'Cannot send value to non-payable function'
-			[creator, { value:1000*money, from: creator}]	+		// await moneyflowInstance.setRootWeiReceiver(creator, {value:1000*money, from:creator}).should.be.rejectedWith('revert');
-		);```

Ну так все логично, конечно. Раньше тест проходил, потому что условие было, что что операция не пройдет. Это более широкий случай, чем что отвалится с ревертом. И раньше работало неправильно, никакого реверта там не может быть, потому что мы просто тупо не можем отправлять деньги на не payable функцию, и именно эта ошибка выскакивает.

> А с другими строками другая проблема – в value отправляется слишком большое значение
Не хватает денег на отправку транзакций, такое вполне может быть, если 100 эфиров, которые даются тестовым аккам, израсходованы в тестах
