### ISSUE TITLE
Moneyflow Scheme gas consumption - evaluate/test/improve

### ISSUE THREAD

**Issue by AnthonyAkentiev** [Thetta/Thetta-DAO-Framework#94]

**Comment by enkogu** [comment]
Only contract creations in constructor: 10 649 600 gas
With connections (addChild): 11 042 816
Empty constructor: 1 212 416
One splitter: 999 424

**Comment by AnthonyAkentiev** [comment]
@enkogu 
1) Deploy to Rinkeby
2) Use compiler optimizations
3) Only for WeiTopDownSplitter

**Comment by enkogu** [comment]
Deploy splitter with optimization to RinkeBy is 824 998 gas
