### ISSUE TITLE
WeiTopDownSplitter - reduce gas costs (use libraries)

### ISSUE THREAD

**Issue by AnthonyAkentiev** [Thetta/Thetta-DAO-Framework#96]
Check these:
1. https://gist.github.com/AnthonyAkentiev/9a49b5bb728e24c0efe737791215a347
2. http://swende.se/blog/EVM-Assembly-trick.html

**Comment by enkogu** [comment]
SplitterStorage gas (only addChild, no interfaces):   245 760 
When .addChild redirect to lib.addChild + interface: 393 216
.addChild calls directly (+interface):                           229 376
extremely minimal implementation(with 4 addresses in constructor): 245 760 
extremely minimal implementation(with 1 address in constructor): 180 224
extremely minimal implementation(with 1 address in constructor): 167 557

**Comment by enkogu** [comment]
Library (with processFunds, some logic in lib)
===========
Splitter gas (first deploy): 638976
Splitter gas (1 child): 606208
Splitter gas (2 children): 622592
Splitter gas (3 children): 655360
Splitter gas (4 children): 655360
Splitter gas (5 children): 688128

**Comment by enkogu** [comment]
Two contracts (main + splitter)
==============
SplitterMain gas: 1015808
Splitter gas (1 child): 573440
Splitter gas (2 children): 589824
Splitter gas (3 children): 622592
Splitter gas (4 children): 638976
Splitter gas (5 children): 655360

**Comment by enkogu** [comment]
SplitterSimple + Controller
===================
SplitterSimple gas (first deploy): 262144
SplitterSimple gas (1 child): 229376
SplitterSimple gas (2 children): 245760
SplitterSimple gas (3 children): 278528
SplitterSimple gas (4 children): 294912
SplitterSimple gas (5 children): 311296
